name: Go Test

on: [ push, pull_request ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21  # SemVer range, or 1.x to match the latest stable Go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd mydirectory
          go test ./...