apiVersion: apps/v1
kind: Deployment
metadata:
  name: spider-deployment
  annotations:
    iam.amazonaws.com/role: ${IAM_ROLE}
  labels:
    app: spider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spider
  template:
    metadata:
      labels:
        app: spider
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: spider
          image: ${SPIDER_IMAGE}
          ports:
            - name: grpc
              containerPort: 9090
            - name: metrics
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"